version "2"

  gateway:
    image: docker-java8:latest
    #image: gateway:201126-1324
    restart: always
    environment:
      - dns-search=dgi.loc 
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@app.test.di.dgi.loc:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@app.test.di.dgi.loc:8761/config
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://app.test.di.dgi.loc:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JDBC_DATABASE_PASSWORD=iRrigacioN2020 
      - JDBC_DATABASE_USERNAME=root 
      - JDBC_DATABASE_URL="jdbc:mysql://database.test.di.dgi.loc:32768/gateway?useUnicode=true&characterEncoding=utf8&use SSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
    ports:
      - 8080:8080
